name: Turtlebot (IA - MLOps - CI/CD)

on:
  push:
    branches: [ main ]

jobs:
  teste_seguranca_agente:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar o Python no servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Instalar dependencias (Gemini, Pytest, etc.)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Executar teste de alucinação do prompt (Gemini)
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        pytest tests/teste_visao.py -v --log-cli-level=INFO