name: Turtlebot (IA - MLOps - CI/CD)

on:
  push:
    branches: [ main ]

jobs:
  teste_seguranca_agente:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar o Python no servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Instalar dependencias (Ollama, Pytest, etc.)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Instalar e Iniciar o Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve &
        sleep 5
        ollama pull qwen2.5:1.5b

    - name: 5. Executar testes de seguranca (visao e Ollama)
      env:
        PYTHONPATH: .
      run: |
        pytest tests/ -v --log-cli-level=INFO